from __future__ import annotations

from typing import Any, Callable


def initialize() -> bool: ...
def free() -> None: ...
def is_ready() -> bool: ...
def get_backend() -> int: ...
def get_capabilities() -> dict[str, bool]: ...
def request_permissions() -> bool: ...
def key_down(key: int, mods: int) -> bool: ...
def key_up(key: int, mods: int) -> bool: ...
def key_repeat(key: int, mods: int) -> bool: ...
def tap(key: int, mods: int) -> bool: ...
def active_modifiers() -> int: ...
def hold_modifiers(mods: int) -> bool: ...
def release_modifiers(mods: int) -> bool: ...
def release_all_modifiers() -> bool: ...
def type_text(text: str) -> bool: ...
def type_character(codepoint: int) -> bool: ...
def flush() -> None: ...
def set_key_delay(delay_us: int) -> None: ...
def start_listener(listener: Callable[[dict[str, Any]], None]) -> bool: ...
def stop_listener() -> None: ...
def is_listening() -> bool: ...
def key_to_string(key: int) -> str | None: ...
def string_to_key(text: str) -> int: ...
def key_to_string_with_modifier(key: int, mods: int) -> str | None: ...
def string_to_key_with_modifier(text: str) -> dict[str, int] | None: ...
def version() -> str: ...
def get_last_error() -> str | None: ...
def clear_last_error() -> None: ...
def log_set_level(level: int) -> None: ...
def log_get_level() -> int: ...
def log_is_enabled(level: int) -> bool: ...
def log_message(level: int, message: str) -> None: ...
